### ISSUE TITLE
Dropping "NativeTypes.FILE" stopped working in Chrome 47

### ISSUE THREAD

**Issue by danielberndt** [gaearon/react-dnd-html5-backend#14]
I've prepared a minimal example here: https://github.com/danielberndt/react-starter/tree/react-dnd-test

When dropping an image, it should be calling the `drop` method but instead the file gets opened in the browser. No warning or error gets issued.

This fails on Chrome 47 on Mac 10.9.5. It works fine on Firefox and used to work fine on earlier versions of Chrome on my machine.

**Comment by danielberndt** [comment]
I did some digging in the code, and it turns out that the `mousemove` event registered [here](https://github.com/gaearon/react-dnd-html5-backend/blob/master/src/HTML5Backend.js#L181) fires too early on Chrome. This is why a `DRAG_END` is fired before the `drop` handler is called, causing the issue.

**Comment by danielberndt** [comment]
Okay, I've just have seen #4. It's fix is probably the cause for this issue here.

**Comment by EvHaus** [comment]
I can confirm. Chrome 47 doesn't seem to be responding to file drop events (even hover). Works fine in Firefox though though.

**Comment by danielberndt** [comment]
current workaround is to use the 2.0.0 version.

**Comment by gaearon** [comment]
Is this still an issue with Chrome 48?

**Comment by gaearon** [comment]
This should be fixed in react-dnd-html5-backend@2.1.2.
