### ISSUE TITLE
dragPreview on a <tr>

### ISSUE THREAD

**Issue by taylor1791** [gaearon/react-dnd-html5-backend#21]
Using `dragPreview` on a `<tr>` does not create a drag image in chrome. This is because of a [bug in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=270932). Should `react-dnd-html5-backend` work around this "quirk"?

Example: In [this](http://jsbin.com/kidoyu/2/edit?js,output) example the `+` sign is the `dragSource`, while the whole row is the dragPreview. Notice that there is no drag image when you try to drag it. 

http://jsbin.com/kidoyu/2/edit?js,output

**Comment by gaearon** [comment]
Thanks for reporting!

> Should react-dnd-html5-backend work around this "quirk"?

I’m afraid this isn’t something that would be easy to work around.
Can’t fix all the quirks :sweat_smile: 

The closest alternative I can offer you is

``` js
  render() {
    return (
      <tr>
        <td>{this.props.dragSource(<span>+</span>)}</td>
        <td>{this.props.dragPreview(<span>{this.props.data.value}</span>)}</td>
      </tr>
    );
  }
```
