### ISSUE TITLE
[Question] Use React primitives

### ISSUE THREAD

**Issue by pspeter3** [gaearon/react-dnd-html5-backend#22]
Reading through the code, it seems that connecting a drag source mutates the DOM nodes and registers handlers as opposed to using React's handlers attribute setting. Is it possible to use React's attribute and event system instead?

If not, is it possible to safely connect the DragSource lazily, during an `onClick` handler?

**Comment by pspeter3** [comment]
It seems like `onMouseDown` would likely be more correct.

**Comment by gaearon** [comment]
Would using React event/attribute system be beneficial here? Why?

**Comment by gaearon** [comment]
I’ll close because I don’t have plans to change this but feel free to continue the discussion.

**Comment by pspeter3** [comment]
I had erroneously believed that connecting a drag source and drop target was performance wise expensive since it was outside of the React render cycle. I do wonder if there would be value since it would mean there is only one system to reason about

**Comment by gaearon** [comment]
I don’t think it’s that expensive _per se_ to be honest. If you check http://gaearon.github.io/react-dnd/examples-sortable-stress.html it works pretty fast despite having 1000 items. Currently backends have no dependency on React and can potentially be reused outside of it, and I’d like to keep them this way.
