### ISSUE TITLE
Retrieve monitor.getItem().files in canDrop function?

### ISSUE THREAD

**Issue by cheemeng** [gaearon/react-dnd-html5-backend#26]
Hi,

I'd like to ensure that:
1. Only 1 file is dragged over, and
2. The file type matches my list of allowed files.

However when I try to retrieve the value of files in the canDrop function, it returns a Browser doesn't allow reading "files" until the drop event.

Are there ways to work around this? Thanks!

**Comment by gaearon** [comment]
Unfortunately not, precisely because

> Browser doesn't allow reading "files" until the drop event.

:wink:
