### ISSUE TITLE
dragPreview broken on Chrome 50?

### ISSUE THREAD

**Issue by N1kto** [gaearon/react-dnd-html5-backend#28]
In our application we started to observe issue with dragging item image. Here is how it looks like:
![no_drag_image](https://cloud.githubusercontent.com/assets/5045863/14776202/280132ba-0ac5-11e6-993a-0deefc16f3a9.gif)

As one can mention _outcome_ items are not drawn at all, while _question_ items are 'screenshotted' without inner text (only grey rectangle).

Reproducible only on **Chrome 50** (checked on **50.0.2661.75**, on **.86** and on **.87m**) . 
On **FF** and **Safari** all works as expected though...
Can it be related to this **Chrome 50** commit: 

> https://chromium.googlesource.com/chromium/src/+/d1e45374111c047fc69c8719434bf14417f74d2e

What can be the way to tackle this issue?

**Comment by yesmeck** [comment]
Save here.

It seems preview image is created after drag started.

http://stackoverflow.com/questions/30887707/html-drag-drop-setdragimage-doesnt-set-ghost-image-on-first-drag

Chaneg this [line](https://github.com/gaearon/react-dnd-html5-backend/blob/master/src%2FHTML5Backend.js#L296) to `dataTransfer.setDragImage(dragPreview.cloneNode(true), dragPreviewOffset.x, dragPreviewOffset.y);` can be a workaround.

**Comment by N1kto** [comment]
@yesmeck thanks for comment. That didn't work. 
I think it's something with the way browser (**Chrome 50**) creates that drag image. That explains why in Chrome 49 and all other browsers all works fine.

**Comment by N1kto** [comment]
Seems like dedicating a layer to drag preview node (by adding CSS `will-change: transform`) 'fixes' the issue. 

![will-change-fix](https://cloud.githubusercontent.com/assets/5045863/14786457/42522946-0aff-11e6-9ca6-e4a6941d08a3.gif)

More and more confident that the issue's root cause comes from mentioned Chrome's commit. Will check with them.

**Comment by N1kto** [comment]
I'll close it for now.
