### ISSUE TITLE
Replace lodash with lodash.<fn> deps

### ISSUE THREAD

**Issue by jakubzitny** [gaearon/react-dnd-html5-backend#41]
Hey there, we're using `react-dnd-html5-backend` from NPM and we're quite surprised by the size of the library. The whole react-dnd is taking 4.7M and almost all of that is only lodash. From lodash you're using only `memoize`, `union`, `without` and `defaults` functions. These are available separately from NPM taking only 148K.

I've already reported similar issue in [react-dnd](https://github.com/gaearon/react-dnd/issues/516) and also #39 might be related to this.

Would you be interested in a PR?

**Comment by billyjanitsch** [comment]
See https://github.com/gaearon/react-dnd/pull/517#issuecomment-244173416.

**Comment by jakubzitny** [comment]
Closing based on the conversation at https://github.com/gaearon/react-dnd/pull/517.
