### ISSUE TITLE
Drop doesn't work in chromium webview elements

### ISSUE THREAD

**Issue by aeneasr** [gaearon/react-dnd-html5-backend#68]
Due to chromium bug [412373](https://bugs.chromium.org/p/chromium/issues/detail?id=412373) this backend isn't workin in chromium webview elements.

I've [read](https://github.com/electron/electron/issues/1276) that setting `dataTransfer.setData('text', /* .. */);` helps, similar to the firefox workaround [`dataTransfer.setData('application/json', {});`](https://github.com/react-dnd/react-dnd-html5-backend/blob/master/src/HTML5Backend.js#L306).

I went ahead an added `dataTransfer.setData('text', 'asdf');` a line before the firefox hack. Now, dropping is at least trinngering the callback, but I'm stuck with this error: `Uncaught Invariant Violation: Cannot call hover while not dragging.` caused by [this line](https://github.com/react-dnd/dnd-core/blob/5a24d23517e249844cb0d7f30ca4708fad40d5b0/src/actions/dragDrop.js#L20).

The code is working fine in a regular browser. Ideas and help greatly appreciated. Chromium bug is fixed but it will take a while before it's released and linked in dependencies like electron.

**Comment by aeneasr** [comment]
This was resolved upstream

**Comment by alexstrat** [comment]
@arekkas upstream: in Chromium? 56 or 57? For instance, in electron v1.6.1 beta (Chrome 56) works for you?

**Comment by aeneasr** [comment]
I didn't upgrade anything actually, but it was a deep dependency which got updated and that is referenced in another dependency with `*`. Removing your npm modules and installing them again might already do the trick.

package.json:

```
"electron": "^1.4.15",
```
